#!/bin/sh

find /var/cache/pkg -type f | while read _pkg; do
	date
	echo "${_pkg}"
	echo
	tar -tvf "${_pkg}" | grep '^-..x' | cut -f 9 -w | while read _file; do
		_symbols=$(tar -OPxf "${_pkg}" "${_file}" | llvm-nm -u - 2>/dev/null)
		if [ $? -ne 0 ]; then
			continue
		fi
		echo "${_symbols}" | grep "$0"
		if [ $? -eq 0 ]; then
			echo "${_pkg}" >&2
			break
		fi
	done
done
